export const SMART_TRAVELLER = "Smart traveller"
export const COUNTRY = "Country"
export const CITY = "City"
export const ADD_TO_VISITED = "Add To Visited"
export const REMOVE = "Remove"
export const ADD_TO_WISHLIST = "Add To Wishlist"
export const VISITED_TOOLTIP = "You have been there !"
export const WISHLIST_TOOLTIP = "Already in Wishlist !"
export const VISITED = "Visited"
export const WISHLIST = "Wishlist"
export const SEARCH_ICON_LABEL = "search-icon"
export const CLOSE_ICON_LABEL = "close-icon"

export const INPUT_BUTTON_HEIGHT = "36px"
export const INPUT_BUTTON_MARGIN = "42px"
export const ROW_HEADING_WIDTH = "150px"
export const TABLE_TOP_MARGIN = "60px"
export const CHECKBOX_ICON_HEIGHT = "40px"
